# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ZonalStatisticsMultiband
                                 A QGIS plugin
 Extends Zonal Statistics official plugin with multiband raster support
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2019-01-30
        copyright            : (C) 2019 by Dymaxion Labs
        email                : damian@dymaxionlabs.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Dymaxion Labs'
__date__ = '2019-01-30'
__copyright__ = '(C) 2019 by Dymaxion Labs'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ZonalStatisticsMultiband class from file ZonalStatisticsMultiband.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .zonal_statistics_multiband import ZonalStatisticsMultibandPlugin
    return ZonalStatisticsMultibandPlugin()
